spring.application.name=MiniPM

# Oracle \uc811\uc18d \uc815\ubcf4
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=scott
spring.datasource.password=kosa1004
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# HikariCP \ucee4\ub125\uc158 \ud480
spring.datasource.hikari.pool-name=IssueFlowPool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# MyBatis Mapper XML \uc704\uce58
mybatis.mapper-locations=classpath:mapper/**/*.xml

# MEMBER_ID \u2192 memberId \uc790\ub3d9 \ubcc0\ud658
mybatis.configuration.map-underscore-to-camel-case=true

# Kakao OAuth2 Provider
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

# Kakao OAuth2 Client
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID}
spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_CLIENT_SECRET}
spring.security.oauth2.client.registration.kakao.client-authentication-method=POST
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,account_email